# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp_read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('dt', models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 30, 22, 59, 55, 923109))),
            ],
        ),
    ]
